
    <div class="wrapper">
        <!-- Navbar -->
       
        <!-- /.navbar -->
        <?php
        include 'navbar.php';
        include "sidebar.php";
        
  
  ?>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            



 <?php
// This provides a default CSS class and placeholder text for the title element:
    $cj = $form->get('codeJury');
    $cj->setAttribute('class', 'form-control');
    $cj->setAttribute('placeholder', 'Code du jury');
    
    $cp = $form->get('codePresident');
    $cp->setAttribute('class', 'form-control');
    $cp->setAttribute('placeholder', 'Code du président du jury');
    
    $cd = $form->get('codeDirecteur');
    $cd->setAttribute('class', 'form-control');
    $cd->setAttribute('placeholder', 'Code directeur de stage');
    
    $cm = $form->get('codeMaitre');
    $cm->setAttribute('class', 'form-control');
    $cm->setAttribute('placeholder', 'Code du maitre de stage');
    
    $ci = $form->get('codeInvite');
    $ci->setAttribute('class', 'form-control');
    $ci->setAttribute('placeholder', 'Code du membre invité');
    

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary ajoutSuccess');

$form->setAttribute('action', $this->url('jury', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>

            <!-- Main content -->
            <section class="content">
                <div class="container">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-6">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Formulaire</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form">
                                    <div class="card-body">

                                        <div class="form-group">
                                            <input type="text" class="type" name="statut" value="0" hidden>
                                        </div>
                                   
                                        <div class="form-group">
                                            
                                            <?= $this->formLabel($cj) ?>
                                            <?= $this->formElement($cj)  ?>
                                            <?= $this->formElementErrors()->render($cj, ['class' => ' help-block']) ?>
                                        </div>
                                         <div class="form-group">
                                            <?= $this->formLabel($cp) ?>
                                            <select class="form-control select2" name="codePresident" style="width: 100%;">

                                                <?php foreach ($albums as $album) : ?>
                                                    <option value=""><?= $this->escapeHtml($album->matricule)  ?></option>  
                                                <?php endforeach; ?>
                                             <!-- <option value="on met ici le code"> et ici on met le nom (ce qui sera visible)</option>  -->
                                             <option value="1452">1452</option>
                                            </select>
                                             <?= $this->formElementErrors()->render($cp, ['class' => ' help-block']) ?>
                                        </div>
                                        
                                         <div class="form-group">
                                            <?= $this->formLabel($cd) ?>
                                            <select class="form-control select2" name="codeDirecteur" style="width: 100%;">
                                                <option selected="selected">4587</option>
                                                
                                                <option>4563</option>
                                                
                                                
                                            </select>
                                             <?= $this->formElementErrors()->render($cd, ['class' => ' help-block']) ?>
                                        </div>
                                         <div class="form-group">
                                            <?= $this->formLabel($cm) ?>
                                            <select class="form-control select2" name="codeMaitre" style="width: 100%;">
                                                <option selected="selected">4879</option>
                                                
                                                <option>1236</option>
                                                
                                                
                                            </select>
                                             <?= $this->formElementErrors()->render($cm, ['class' => ' help-block']) ?>
                                        </div>
                                        <div class="form-group">
                                            <?= $this->formLabel($ci) ?>
                                            <select class="form-control select2" name="codeInvite" style="width: 100%;">
                                                <option selected="selected">7896</option>
                                                
                                                <option>6985</option>
                                                
                                                
                                            </select>
                                             <?= $this->formElementErrors()->render($ci, ['class' => ' help-block']) ?>
                                        </div>
                                     
                                     
                                        <div class="card-footer">
                                        
                                        
                                            <?php
                                            echo $this->formSubmit($submit);
                                            echo $this->formHidden($form->get('id'));
                                            echo $this->form()->closeTag();?>
                                        </div>
                                        
                                    </div>
                                    <!-- /.card-body -->

                                    
                                </form>
                            </div>
                           

                        </div>
                      
                          
                        </div>
                        <!--/.col (right) -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <?php
    include "footer.php";

  ?>

