
<div class="wrapper">

  <!-- Navbar -->
 
  <!-- /.navbar -->
  <?php
  include "navbar.php";
  include "sidebar.php";
  ?>

 
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <!-- <h1 class="m-0 text-dark">Dashboard</h1> -->
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Accueil</a></li> -->
              <!-- <li class="breadcrumb-item active">Dashboard v1</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
  

    <!-- section fictive juste pour tester les anciens codes -->

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
   

          
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">La liste des Jury</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="listeEtud" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>Code Jury</th>
                      <th>President de jury</th>
                      <th>Directeur de stage</th>
                      <th>Maitre de stage</th>
                      <th>Membre invite</th>
                      <th>Actions <i class="fa fa-cogs"></i></th>
                  </tr>
                  </thead>
                  <tbody>
                  <?php foreach ($jurys as $jury) : ?>
                 
                      <tr>
                          <td><?= $this->escapeHtml($jury->codeJury) ?></td>
                          <td><?= $this->escapeHtml($jury->codePresident) ?> </td>
                          <td><?= $this->escapeHtml($jury->codeDirecteur) ?></td>
                          <td><?= $this->escapeHtml($jury->codeMaitre) ?></td>
                          <td><?= $this->escapeHtml($jury->codeInvite) ?></td>
                      
                          <td>
                              <a href="<?= $this->url('jury', ['action' => 'edit', 'id' => $jury->id]) ?>" class="btn btn-info btn-sm"><i class="far fa-edit"></i>Editer</a>
                              <!-- <a href="<?//= $this->url('jury', ['action' => 'delete', 'id' => $jury->id]) ?>" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger"><i class="fa fa-trash-alt"></i>Supprimer</a> -->
                              <a href="<?= $this->url('jury', ['action' => 'delete', 'id' => $jury->id]) ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash-alt"></i>Supprimer</a>
                          </td>
                      </tr>
                  <?php endforeach; ?>
            
               
                  </tbody>
                  <tfoot>
                 <tr>
                     <th>Code Jury</th>
                      <th>President de jury</th>
                      <th>Directeur de stage</th>
                      <th>Maitre de stage</th>
                      <th>Membre invite</th>
                      <th>Actions <i class="fa fa-cogs"></i></th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <?php
    include "footer.php";
  ?>

