
    <div class="wrapper">
        <!-- Navbar -->
       
        <!-- /.navbar -->
        <?php
        include 'navbar.php';
        include "sidebar.php";
        
  
  ?>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            



 <?php
// This provides a default CSS class and placeholder text for the title element:

 use Album\Model\Jury;
use Album\Form\JuryForm;
use Album\Model\JuryTable;
use Album\Model\PresidentTable;
use Laminas\Mvc\Controller\AbstractActionController;
use Laminas\View\Model\ViewModel;
      $form = new JuryForm();
        $form->get('submit')->setValue('Ajouter');
 

    $cj = $form->get('codeJury');
    $cj->setAttribute('class', 'form-control');
    $cj->setAttribute('placeholder', 'Code du jury');
    
    $cp = $form->get('codePresident');
    $cp->setAttribute('class', 'form-control');
    $cp->setAttribute('placeholder', 'Président du jury');
    
    $cd = $form->get('codeDirecteur');
    $cd->setAttribute('class', 'form-control');
    $cd->setAttribute('placeholder', 'Directeur de stage');
    
    $cm = $form->get('codeMaitre');
    $cm->setAttribute('class', 'form-control');
    $cm->setAttribute('placeholder', 'Maitre de stage');
    
    $ci = $form->get('codeInvite');
    $ci->setAttribute('class', 'form-control');
    $ci->setAttribute('placeholder', 'Membre invité');
    

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary ajoutSuccess');
   $request = $this->getRequest();

        if (! $request->isPost()) {
            return ['form' => $form];
        }

        $jury = new Jury(); 
        $form->setInputFilter($jury->getInputFilter());
        $form->setData($request->getPost());

        if (! $form->isValid()) {
            return ['form' => $form];
        }
  
        $jury->exchangeArray($form->getData());
        $this->table->saveJury($jury);
        return $this->redirect()->toRoute('listej'); 

$form->setAttribute('action', $this->url('jury', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);

?>


            <!-- Main content -->
            <section class="content">
                <div class="container">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-6">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Formulaire</h3>
                                   
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form">
                                    <div class="card-body">
                                   
                                        <div class="form-group">
                                            
                                            <?= $this->formLabel($cj) ?>
                                            <?= $this->formElement($cj)  ?>
                                        </div>

                                        <div class="form-group">
                                            <?= $this->formLabel($cp) ?>
                                            <select class="form-control select2" name="codePresident" style="width: 100%;">
                                                   

                                                <?php
                                            
                                                var_dump(president);
                                                foreach ($president as $president) : ?>
                                                     
                                                    <option><?= $this->escapeHtml($president->nomPresident) ?><?= $this->escapeHtml($president->prenomPresident) ?></option>  
                                                <?php endforeach; ?>
                                             <!-- <option value="on met ici le code"> et ici on met le nom (ce qui sera visible)</option>  -->
                                             
                                            </select>
                                        </div>
                                        
                                         <div class="form-group">
                                            <?= $this->formLabel($cd) ?>
                                            <select class="form-control select2" name="codeDirecteur" style="width: 100%;">
                                                <option selected="selected">4587</option>
                                                
                                                <option>4563</option>
                                                
                                                
                                            </select>
                                             
                                        </div>
                                         <div class="form-group">
                                            <?= $this->formLabel($cm) ?>
                                            <select class="form-control select2" name="codeMaitre" style="width: 100%;">
                                                <option selected="selected">4879</option>
                                                
                                                <option>1236</option>
                                                
                                                
                                            </select>
                                          
                                        </div>
                                        <div class="form-group">
                                            <?= $this->formLabel($ci) ?>
                                            <select class="form-control select2" name="codeInvite" style="width: 100%;">
                                                <option selected="selected">7896</option>
                                                
                                                <option>6985</option>
                                                
                                                
                                            </select>
                                        
                                        </div>
                                     
                                     
                                        <div class="card-footer">
                                        
                                        
                                            <?php
                                            echo $this->formSubmit($submit);
                                            echo $this->formHidden($form->get('id'));
                                            echo $this->form()->closeTag();?>
                                        </div>
                                        
                                    </div>
                                    <!-- /.card-body -->

                                    
                                </form>
                            </div>
                           

                        </div>
                      
                          
                        </div>
                        <!--/.col (right) -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <?php
    include "footer.php";

  ?>

