
<div class="wrapper">

  <!-- Navbar -->
 
  <!-- /.navbar -->
  <?php
  include "navbar.php";
  include "sidebar.php";
  ?>

 
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
           <h1 class="m-0 text-dark">Liste des membres invités</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Accueil</a></li> -->
              <!-- <li class="breadcrumb-item active">Dashboard v1</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
  

    <!-- section fictive juste pour tester les anciens codes -->

    <section class="content">
      <!-- Default box -->
      <div class="card card-solid">
        <div class="card-body pb-0">
          <div class="row d-flex align-items-stretch">


            <?php foreach ($membres as $membre) : ?>
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
              <div class="card bg-light">
                <div class="card-header text-muted border-bottom-0">
                  <?= $this->escapeHtml($membre->gradeInvite) ?>
                </div>
                <div class="card-body pt-0">
                  <div class="row">
                    <div class="col-7">
                      <h2 class="lead"><b><?= $this->escapeHtml($membre->prenomInvite) ?></b> <strong><?= $this->escapeHtml($membre->nomInvite) ?></strong></h2>
                      <p class="text-muted text-sm"><b>Sexe: </b> <?= $this->escapeHtml($membre->sexeInvite) ?> </p>
                    

                      <ul class="ml-4 mb-0 fa-ul text-muted">
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Adresse: <?= $this->escapeHtml($membre->adresseInvite) ?></li>
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-code"></i></span> Code #: <?= $this->escapeHtml($membre->codeInvite) ?></li>
                      </ul>
                    </div>
                    <div class="col-5 text-center">
                      <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="text-right">
                    <a href="<?= $this->url('membre', ['action' => 'edit', 'id' => $membre->id]) ?>" class="btn btn-sm bg-primary"><i class="far fa-edit"></i>Editer</a>
                    <a href="<?= $this->url('membre', ['action' => 'delete', 'id' => $membre->id]) ?>" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i> Supprimer</a>
                  </div>
                </div>
              </div>
            </div>
            <?php endforeach; ?>

            


          </div> 
        </div> 
      </div>            
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <?php
    include "footer.php";
  ?>
  